### ISSUE TITLE
problem with hyper :(

### ISSUE THREAD

**Issue by MAPESO** [delcore92/hyper-match#1]
- **OS version and name**: macOS high sierra and Windows 10
- **Hyper.app version**: 1.4.8 and canary version(2.0.4)

Disables writing in Hyper

 
Windows 10
![22219451_1149860821824173_744382452_o](https://user-images.githubusercontent.com/16585386/31116021-20168c94-a7ea-11e7-9d46-80dcb5d03d2a.png)

macOS
<img width="1280" alt="screen shot 2017-10-02 at 19 48 30" src="https://user-images.githubusercontent.com/16585386/31116040-30f6d2b2-a7ea-11e7-93e6-d2b72f84b287.png">

**Comment by delcore92** [comment]
Hi Mark, thanks again for looking into this for me!
Are you able to share the logs from the developer console if there are any? 
Also, i notice that you have `hyperlinks` and `hyper-match` installed at the same time. Because `hyper-match` is built on top of `hyperlinks` they will likely clash with each other, try disabling `hyperlinks` and see if your error persists.

**Comment by MAPESO** [comment]
@delcore92 I just remove the **hyperlinks** plugin. But the result remains the same ☹️
<img width="1280" alt="screen shot 2017-10-06 at 19 07 02" src="https://user-images.githubusercontent.com/16585386/31302763-f0146470-aac9-11e7-8414-4ad84d9d193b.png">

**Comment by MAPESO** [comment]
@delcore92 It is very strange the error that is occurring with stable version.
<img width="1280" alt="screen shot 2017-10-06 at 19 15 22" src="https://user-images.githubusercontent.com/16585386/31302845-c150853c-aaca-11e7-9a7c-09ece56e2a44.png">

**Comment by delcore92** [comment]
Hi @MAPESO, 
I just found an issue in the scenario that there is no `hyper-match` configuration. 
This will throw an error when i try to access that configuration. I'll raise a pr to fix it now, cheers 👍

**Comment by delcore92** [comment]
Just pushed a fix, please see v0.1.3 👍
